export enum Role {
    ROLE_MANAGER = 'ROLE_MANAGER',
    ROLE_OPERATOR = 'ROLE_OPERATOR',
    ROLE_DATA = 'ROLE_DATA',

    ROLE_SERVER_REST_ACCESS = 'ROLE_SERVER_REST_ACCESS',
    ROLE_ASSET_REST_ACCESS = 'ROLE_ASSET_REST_ACCESS',
    ROLE_BILLING = 'ROLE_BILLING',

    ROLE_MAIN_ADMIN = 'ROLE_MAIN_ADMIN',
    ROLE_MAIN_OPERATOR = 'ROLE_MAIN_OPERATOR',
    ROLE_MAIN_SUPPORT = 'ROLE_MAIN_SUPPORT',
    ROLE_MAIN_ASSET_MANAGER = 'ROLE_MAIN_ASSET_MANAGER',

    ROLE_ADMIN = 'ROLE_ADMIN',

    // --

    Manager = 'ROLE_MANAGER',
    Operator = 'ROLE_OPERATOR',
    Data = 'ROLE_DATA',

    ServerrestAccess = 'ROLE_SERVER_REST_ACCESS',
    AssetRestAccess = 'ROLE_ASSET_REST_ACCESS',
    Billing = 'ROLE_BILLING',

    MainAdmin = 'ROLE_MAIN_ADMIN',
    MainOperator = 'ROLE_MAIN_OPERATOR',
    MainSupport = 'ROLE_MAIN_SUPPORT',
    MainAssetManager = 'ROLE_MAIN_ASSET_MANAGER',

    Admin = 'ROLE_ADMIN'

}